#!/bin/sh
set -e

if [ -z ${AWS_REGION+x} ]; then
    echo "Missing ENV variable AWS_REGION"
    exit 1
fi
if [ -z ${AWS_SECRET_ACCESS_KEY+x} ]; then
    echo "Missing ENV variable AWS_SECRET_ACCESS_KEY"
    exit 1
fi
if [ -z ${AWS_ACCESS_KEY_ID+x} ]; then
    echo "Missing ENV variable AWS_ACCESS_KEY_ID"
    exit 1
fi

# the config files might be totaly unnecessary but it was buggy without them
cat >/root/.aws/config <<EOL
[default]
region = ${AWS_REGION}
EOL

cat >/root/.aws/credentials <<EOL
[default]
aws_access_key_id = ${AWS_ACCESS_KEY_ID}
aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}
EOL

exec "$@"
